[package]
name = "psbt-v2"
version = "0.3.0"
authors = ["Tobin C. Harding <me@tobin.cc>"]
license = "CC0-1.0"
repository = "https://git.rust-bitcoin.org/rust-bitcoin/rust-psbt"
description = "Partially Signed Bitcoin Transaction, v0 and v2"
categories = ["cryptography::cryptocurrencies"]
keywords = [ "psbt", "bip-174", "bip174", "bip-370", "bip370"]
readme = "README.md"
edition = "2021"
rust-version = "1.74.0"
exclude = ["api", "tests", "contrib"]

[package.metadata]
rbmt.version = "0.5.3"

[package.metadata.rbmt.toolchains]
nightly = "nightly-2026-08-01"
stable = "1.97.1"

[package.metadata.rbmt.tools]
cargo-mutants = "27.1.0"

[package.metadata.rbmt.test]
examples = [
    "v0:std rand",
    "v2:std",
    "v2-separate-creator-constructor:std",
]
exact_features = [
    ["std", "miniscript", "serde"],
]

[package.metadata.rbmt.lint]
allowed_duplicates = [
  # Required until we drop the 0.32 series of bitcoin.
  "hex-conservative",
]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["std"]
std = ["bitcoin/std", "bitcoin-consensus-encoding/std", "miniscript?/std"]
rand = ["std", "bitcoin/rand-std"]
serde = ["dep:serde", "bitcoin/serde", "bitcoin-consensus-encoding/serde"]
base64 = ["bitcoin/base64"]
silent-payments = [] # Silent Payments support

[dependencies]
bitcoin = { version = "0.32.102", default-features = false, features = ["encoding"] }
bitcoin-consensus-encoding = { version = "1.2.0", default-features = false, features = ["alloc", "hex"] }

arbitrary = { version = "1.0.1", optional = true }
miniscript = { version = "13.1.0", default-features = false, optional = true }
serde = { version = "1.0.195", default-features = false, features = ["derive", "alloc"], optional = true }

[dev-dependencies]
anyhow = "1.0.86"
serde_json = "1.0.68"

[[example]]
name = "v0"
required-features = ["std", "rand"]

[[example]]
name = "v2"
required-features = ["std"]

[[example]]
name = "v2-separate-creator-constructor"
required-features = ["std"]

[lints.clippy]
redundant_clone = "warn"
use_self = "warn"
