name: Setup RBMT
description: Install cargo-rbmt and toolchains for workspace

runs:
  using: composite
  steps:
    - name: Install cargo-rbmt
      shell: bash
      run: |
        cargo install \
          --locked \
          cargo-rbmt@$(grep "^rbmt.version" Cargo.toml | cut -d'"' -f2)

    - name: Install toolchains
      shell: bash
      run: cargo rbmt toolchains

    - name: Install tools
      shell: bash
      run: cargo rbmt tools
