---
# rust-psbt CI
#
# CI job and task structure is optimized for developer debugging. Not runner
# minutes or parallelism.

on:   # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:

name: Continuous Integration

jobs:
  Test:
    runs-on: debian-trixie
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, msrv]
        dep: [minimal, maximum]
    steps:
      - uses: https://data.forgejo.org/actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6
        with:
          fetch-depth: 0 # Context required for bisectability tests.
          persist-credentials: false
      - uses: ./.forgejo/actions/setup-rbmt
      - name: "Run tests"
        run: cargo rbmt test --lockfile ${{ matrix.dep }} --toolchain ${{ matrix.toolchain }} --baseline ${{ forgejo.event.pull_request.base.sha || forgejo.event.before }}

  Check:
    runs-on: debian-trixie
    strategy:
      fail-fast: false
      matrix:
        command: [lint, docs]
    steps:
      - uses: https://data.forgejo.org/actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6
      - uses: ./.forgejo/actions/setup-rbmt
      - name: "Run check"
        run: cargo rbmt ${{ matrix.command }} --lockfile maximum

  Integration:
    runs-on: debian-trixie
    steps:
      - uses: https://data.forgejo.org/actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6
      - uses: ./.forgejo/actions/setup-rbmt
      - name: "Run bitcoind integration tests"
        run: cargo rbmt integration

  Format:
    runs-on: debian-trixie
    steps:
      - uses: https://data.forgejo.org/actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6
      - uses: ./.forgejo/actions/setup-rbmt
      - name: "Check format"
        run: cargo rbmt fmt --check

  Fuzz:
    runs-on: debian-trixie
    steps:
      - uses: https://data.forgejo.org/actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6
      - uses: ./.forgejo/actions/setup-rbmt
      - name: "Check fuzz targets"
        working-directory: fuzz
        run: |
          cargo rbmt tools
          cargo +$(cargo rbmt toolchains --nightly) fuzz check

  Mutants:
    runs-on: debian-trixie
    steps:
      - uses: https://data.forgejo.org/actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6
        with:
          fetch-depth: 0 # History required to diff against the baseline.
      - uses: ./.forgejo/actions/setup-rbmt
      - name: "Check mutants"
        run: git diff ${{ forgejo.event.pull_request.base.sha || forgejo.event.before }} | cargo +$(cargo rbmt toolchains --nightly) mutants --in-diff /dev/stdin -- -- -Z unstable-options --fail-fast --nocapture
