---
# rust-psbt CI
#
# CI job and task structure is optimized for developer debugging. Not runner
# minutes or parallelism.

on:   # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:

name: Continuous Integration

jobs:
  Test:
    runs-on: debian-trixie
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, msrv]
        dep: [minimal, recent]
    steps:
      - uses: https://data.forgejo.org/actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6
        with:
          fetch-depth: 0 # Context required for bisectability tests.
          persist-credentials: false
      - uses: ./.forgejo/actions/setup-rbmt
      - name: "Run tests"
        run: cargo rbmt --lock-file ${{ matrix.dep }} test --toolchain ${{ matrix.toolchain }} --baseline ${{ forgejo.event.pull_request.base.sha || forgejo.event.before }}

  Check:
    runs-on: debian-trixie
    strategy:
      fail-fast: false
      matrix:
        command: [lint, api, docs, docsrs, integration, "fmt --check"]
    steps:
      - uses: https://data.forgejo.org/actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6
      - uses: ./.forgejo/actions/setup-rbmt
      - name: "Run ${{ matrix.command }}"
        run: cargo rbmt ${{ matrix.command }}

  Fuzz:
    runs-on: debian-trixie
    steps:
      - uses: https://data.forgejo.org/actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v6
      - uses: https://git.rust-bitcoin.org/rust-bitcoin/rust-bitcoin-maintainer-tools/actions/setup-rbmt@46d459105f770106a2812641a54bd0e24bb57395
      - name: "Check fuzz targets"
        working-directory: fuzz
        run: cargo rbmt tools && cargo rbmt run --toolchain nightly --lock-file existing -- fuzz check
