[package]
name = "rust-psbt-fuzz"
version = "0.0.0"
publish = false
edition = "2021"
rust-version = "1.74.0"

[package.metadata]
cargo-fuzz = true

[package.metadata.rbmt.tools]
cargo-fuzz = "0.13.2"

[package.metadata.rbmt.toolchains]
nightly = "nightly-2026-07-21"

[dependencies]
libfuzzer-sys = "0.4"
psbt-v2 = { path = "..", features = ["arbitrary"] }

[[bin]]
name = "deserialize_v0"
path = "fuzz_targets/deserialize_v0.rs"
test = false
doc = false
bench = false
