export RBMT_LOG_LEVEL := env("RBMT_LOG_LEVEL", "progress")

_default:
	@just --list

# Install tools.
@tools:
	cargo install --quiet --locked cargo-rbmt@$(grep "^rbmt.version" {{justfile_directory()}}/../Cargo.toml | cut -d'"' -f2)
	cargo rbmt tools

# Cycle all targets.
@cycle: tools
    nightly=$(cargo rbmt toolchains --nightly) && \
    for target in $(cargo +$nightly fuzz list); do \
        cargo +$nightly fuzz run "$target" -- -max_total_time=10; \
    done
