_default:
	@just --list

# Install tools.
@tools:
	cargo install --quiet --git https://git.rust-bitcoin.org/rust-bitcoin/rust-bitcoin-maintainer-tools --rev $(cat {{justfile_directory()}}/../rbmt-version) cargo-rbmt
	RBMT_LOG_LEVEL=progress cargo rbmt toolchains
	RBMT_LOG_LEVEL=progress cargo rbmt tools

# Cycle all targets.
@cycle: tools
	for target in $(cargo rbmt run --toolchain nightly --lock-file existing -- fuzz list); do cargo rbmt run --toolchain nightly --lock-file existing -- fuzz run "$target" -- -max_total_time=10; done
