additional_cargo_args = ["--all-features"]

exclude_globs = [
    "src/v0/**", # Deprecated and slated for removal.
]

exclude_re = [
    # Standard
    "<impl fmt::Display for .*Error>::fmt", # Error message formatting
    "std::error::Error for",                # Error source boilerplate
    "<impl From<[^>]+> for .*Error>::from", # Error conversion boilerplate
    "Iterator",                             # Mutating operations in an iterator can result in an infinite loop
    # Encoding
    "PsbtDecode::psbt_decoder",             # Default mutant is equivalent to implementation, can't squash.
]
