[package]
name = "bitcoind-tests"
version = "0.1.0"
authors = ["Tobin C. Harding <me@tobin.cc>"]
license = "CC0-1.0"
edition = "2021"
publish = false

[package.metadata.rbmt.toolchains]
stable = "1.98.0"

[dependencies]

bitcoind = { version = "0.38.0", features = ["download"] }
psbt-v2 = { path = "..", features = ["std", "miniscript", "rand"] }

[dev-dependencies]

[features]
# Bitcoin Core version range integration testing.
# Starting from 0.17.0 because that's when PSBT v0 (BIP-174) was first introduced.
# v30.2 is latest, Bitcoin Core will support PSBT v2 (BIP-370) soon, possible v32.
"30_2" = ["bitcoind/30_2"]
"0_17_2" = ["bitcoind/0_17_2"]
