name: 'Prepare Rust Environment'
description: 'Setup Rust toolchain and install RBMT'
inputs:
  toolchain:
    description: 'Rust toolchain to use (nightly reads from nightly-version file)'
    required: false
    default: 'stable'
  components:
    description: 'Rust components to install (e.g., clippy, rustfmt)'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: "Install ARM cross-compiler for no-std"
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get install -y gcc-arm-none-eabi
        echo "CC_thumbv7m_none_eabi=arm-none-eabi-gcc" >> $GITHUB_ENV

    - name: "Determine toolchain"
      id: toolchain
      shell: bash
      run: |
        [[ "${{ inputs.toolchain }}" == "nightly" ]] && TOOLCHAIN=$(cat nightly-version) || TOOLCHAIN="${{ inputs.toolchain }}"
        echo "version=$TOOLCHAIN" >> $GITHUB_OUTPUT

    - name: "Setup requested toolchain"
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable,${{ steps.toolchain.outputs.version }}
        components: ${{ inputs.components }}
        target: thumbv7m-none-eabi

    - name: "Install RBMT"
      shell: bash
      run: cargo +stable install --git https://github.com/rust-bitcoin/rust-bitcoin-maintainer-tools.git --rev "$(cat rbmt-version)" cargo-rbmt --locked
